stages:
  - deploy

deploy_manual_job:
  stage: deploy
  image: alpine:latest  # Lightweight image with SSH
  before_script:
    - apk update && apk add --no-cache openssh-client sshpass git
  script:
    - echo "🚀 Starting deployment on live server 110.34.2.30"

    # SSH config setup
    - mkdir -p ~/.ssh
    - echo -e "Host live-server\n  HostName 110.34.2.30\n  Port 23\n  User devops" > ~/.ssh/config
    - chmod 600 ~/.ssh/config

    # SSH into the server and run deployment steps
    - |
      sshpass -p "$hsm_server_pwd" ssh -o StrictHostKeyChecking=no devops@110.34.2.30 -p 23 "
        set -e
        echo '🔧 Creating deployment directory...'
        mkdir -p /home/hsmdevops/library-api-system
        cd /home/hsmdevops/library-api-system

        echo ' Cloning repository using GitLab access token...'
        git clone -b main https://oauth2:${hsm_test_repo_token}@gitlab.com/<your-group>/<your-repo>.git . || true

        echo '🐳 Running deployment script...'
        chmod +x DevOps/deploy.sh
        ./DevOps/deploy.sh

        echo ' Checking container status...'
        docker ps -a | grep -E 'CONTAINER|aayush-'

        echo ' Displaying recent logs...'
        docker compose -f DevOps/docker-compose.yml logs --tail=50

        echo ' Deployment completed on live server.'
      "
  only:
    - main
  when: manual